return {
PlaceObj('ModItemCode', {
	'name', "RSBDisasterControl",
	'FileName', "Code/RSBDisasterControl.lua",
}),
PlaceObj('ModItemCode', {
	'name', "RSBResearch",
	'FileName', "Code/RSBResearch.lua",
}),
PlaceObj('ModItemCode', {
	'name', "RSBResearchMap",
	'FileName', "Code/RSBResearchMap.lua",
}),
PlaceObj('ModItemTech', {
	'name', "RSBBreakthroughBiotech",
	'id', "RSBBreakthroughBiotech",
	'display_name', T{361773802745, "Biotech deep research"},
	'icon', "UI/Icons/Research/biome_engineering.tga",
	'description', T{361773802799, "Advanced research in biotech. Tries to find a new breakthrough in biotech.<newline>Makes all colonists <param1comment> <param1>% less food when failed.<newline>After reaching minimal consumption rate grants <param2>% bonus to all funding gains."},
	'position', range(5, 5),
	'repeatable', true,
	'param1comment', "Consumption food decrease per fail <param1>%",
	'param1', 2,
	'param2comment', "Consumption minimum",
	'param2', 10,
	'param5comment', "Funding gain per fail",
	'param5', 2,
	'field', "Biotech",
}),
PlaceObj('ModItemTech', {
	'name', "RSBBreakthroughEngineering",
	'id', "RSBBreakthroughEngineering",
	'display_name', T{736758121526, "Engineering deep research"},
	'icon', "UI/Icons/Research/mars_nouveau.tga",
	'description', T{736758121599, "Advanced research in engineering. Tries to find a new breakthrough in enginnering.<newline>"},
	'position', range(5, 5),
	'repeatable', true,
	'param1', 500,
	'param2', 5000,
	'param5comment', "Funding gain per fail",
	'param5', 2,
	'field', "Engineering",
}),
PlaceObj('ModItemTech', {
	'name', "RSBBreakthroughPhysics",
	'id', "RSBBreakthroughPhysics",
	'display_name', T{908591358810, "Physics deep research"},
	'icon', "UI/Icons/Research/atomic_accumulator.tga",
	'description', T{908591358899, "Advanced research in engineering. Tries to find a new breakthrough in physics.<newline>Increases research output from electricity surplus when failed.<newline>After reaching minimal consumption rate grants bonus to all funding gains."},
	'position', range(5, 5),
	'repeatable', true,
	'param1comment', "Electricity units per research points (100 = 1EU)",
	'param1', 500,
	'param2comment', "Electricity minimum",
	'param2', 5000,
	'param3comment', "Initial electricity conversion rate",
	'param3', 20000,
	'param5comment', "Funding gain per fail",
	'param5', 2,
	'field', "Physics",
}),
PlaceObj('ModItemTech', {
	'name', "RSBBreakthroughRobotics",
	'id', "RSBBreakthroughRobotics",
	'display_name', T{747721283307, "Robotics deep research"},
	'icon', "UI/Icons/Research/rover_command_ai.tga",
	'description', T{747721283399, "Advanced research in robotics: tries to find a new breakthrough in robotics.<newline>Increases all automated performance if failed by <param1>% up to <param2>% limit.<newline>After reaching maximum peformance grants <param5>% bonus to all funding gains."},
	'position', range(5, 5),
	'repeatable', true,
	'param1comment', "Automated robotics performance bonus, %",
	'param1', 5,
	'param2comment', "Automated robotics performance max, %",
	'param2', 100,
	'param5comment', "Funding gain per fail",
	'param5', 2,
	'field', "Robotics",
}),
PlaceObj('ModItemTech', {
	'name', "RSBBreakthroughSocial",
	'id', "RSBBreakthroughSocial",
	'display_name', T{930113112848, "Social deep research"},
	'icon', "UI/Icons/Research/general_training.tga",
	'description', T{930113112899, "Advanced research in social.<newline>Tries to find a new breakthrough in social.<newline>Gives <param5>% to all funding gains when failed."},
	'position', range(5, 5),
	'repeatable', true,
	'param5comment', "Funding gain per fail",
	'param5', 5,
	'field', "Social",
}),
}
