return {
PlaceObj('ModItemBuildingTemplate', {
	'name', "RSBSolarPanel",
	'template_class', "RSBSolarPanel",
	'pin_rollover_context', "electricity",
	'pin_rollover_hint', T{919746971896, --[[ModItemBuildingTemplate RSBSolarPanel pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Select"},
	'pin_rollover_hint_xbox', T{373489128691, --[[ModItemBuildingTemplate RSBSolarPanel pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> View"},
	'construction_cost_Metals', 1000,
	'build_points', 500,
	'show_range_class', "ArtificialSun",
	'maintenance_resource_type', "Metals",
	'maintenance_resource_amount', 500,
	'display_name', T{569996355890, --[[ModItemBuildingTemplate RSBSolarPanel display_name]] "Solar Panel"},
	'display_name_pl', T{444406584772, --[[ModItemBuildingTemplate RSBSolarPanel display_name_pl]] "Solar Panels"},
	'description', T{902779465160, --[[ModItemBuildingTemplate RSBSolarPanel description]] "Generates Power during daytime. Its effectiveness is decreased by dust accumulation and during sand storms. Protected from dust while turned off."},
	'build_category', "Power",
	'display_icon', "UI/Icons/Buildings/solar_panel.tga",
	'entity', "SolarPanel",
	'encyclopedia_image', "UI/Encyclopedia/SolarPanel.tga",
	'build_shortcut1', "N",
	'label1', "OutsideBuildings",
	'label2', "OutsideBuildingsTargets",
	'palettes', "Outside_01",
	'demolish_sinking', range(5, 15),
	'demolish_tilt_angle', range(300, 600),
	'electricity_production', 2000,
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "RSBSolarPanelBig",
	'template_class', "RSBSolarPanelBig",
	'pin_rollover_context', "electricity",
	'pin_rollover_hint', T{431278605836, --[[ModItemBuildingTemplate RSBSolarPanelBig pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Select"},
	'pin_rollover_hint_xbox', T{532025867199, --[[ModItemBuildingTemplate RSBSolarPanelBig pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> View"},
	'construction_cost_Metals', 4000,
	'build_points', 1500,
	'show_range_class', "ArtificialSun",
	'maintenance_resource_type', "Metals",
	'display_name', T{268750711385, --[[ModItemBuildingTemplate RSBSolarPanelBig display_name]] "Large Solar Panel"},
	'display_name_pl', T{247333503709, --[[ModItemBuildingTemplate RSBSolarPanelBig display_name_pl]] "Large Solar Panel"},
	'description', T{932749897888, --[[ModItemBuildingTemplate RSBSolarPanelBig description]] "Generates Power during daytime. Its effectiveness is decreased by dust accumulation and during Dust Storms. Protected from dust while turned off."},
	'build_category', "Power",
	'display_icon', "UI/Icons/Buildings/solar_aray.tga",
	'build_pos', 2,
	'entity', "SolarPanelBig",
	'encyclopedia_image', "UI/Encyclopedia/LargeSolarPanel.tga",
	'build_shortcut1', "J",
	'label1', "OutsideBuildings",
	'label2', "OutsideBuildingsTargets",
	'palettes', "SolarPanelBig",
	'demolish_sinking', range(5, 15),
	'demolish_tilt_angle', range(300, 600),
	'demolish_debris', 80,
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "RSBStirlingGenerator",
	'template_class', "RSBStirlingGenerator",
	'pin_rollover_context', "electricity",
	'pin_rollover_hint', T{385464141286, --[[ModItemBuildingTemplate RSBStirlingGenerator pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Select"},
	'pin_rollover_hint_xbox', T{956498400567, --[[ModItemBuildingTemplate RSBStirlingGenerator pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> View"},
	'construction_cost_Polymers', 12000,
	'construction_cost_Electronics', 6000,
	'build_points', 1000,
	'require_prefab', true,
	'upgrade1_id', "StirlingGenerator_PlutoniumCore",
	'upgrade1_display_name', T{338422841863, --[[ModItemBuildingTemplate RSBStirlingGenerator upgrade1_display_name]] "Plutonium Core"},
	'upgrade1_description', T{296384540016, --[[ModItemBuildingTemplate RSBStirlingGenerator upgrade1_description]] "+<upgrade1_mul_value_1>% additional power production when open."},
	'upgrade1_icon', "UI/Icons/Upgrades/plutonium_core_01.tga",
	'upgrade1_upgrade_cost_Polymers', 4000,
	'upgrade1_mod_label_1', "StirlingGenerator",
	'upgrade1_mod_prop_id_1', "production_factor_interacted",
	'upgrade1_mul_value_1', 50,
	'maintenance_resource_type', "Polymers",
	'display_name', T{157352179067, --[[ModItemBuildingTemplate RSBStirlingGenerator display_name]] "Stirling Generator"},
	'display_name_pl', T{474399873447, --[[ModItemBuildingTemplate RSBStirlingGenerator display_name_pl]] "Stirling Generators"},
	'description', T{446501445653, --[[ModItemBuildingTemplate RSBStirlingGenerator description]] "Generates Power. While closed the generator is protected from dust, but produces less power."},
	'build_category', "Power",
	'display_icon', "UI/Icons/Buildings/stirling_generator.tga",
	'build_pos', 4,
	'entity', "StirlingGenerator",
	'encyclopedia_image', "UI/Encyclopedia/StirlingGenerator.tga",
	'label1', "OutsideBuildings",
	'label2', "OutsideBuildingsTargets",
	'palettes', "StirlingGenerator",
	'demolish_sinking', range(5, 10),
	'demolish_tilt_angle', range(300, 600),
	'demolish_debris', 80,
	'electricity_production', 10000,
	'production_factor_interacted', 200,
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "RSBSubsurfaceHeater",
	'template_class', "RSBSubsurfaceHeater",
	'pin_rollover_hint', T{693115674478, --[[ModItemBuildingTemplate RSBSubsurfaceHeater pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Select"},
	'pin_rollover_hint_xbox', T{936661321890, --[[ModItemBuildingTemplate RSBSubsurfaceHeater pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> View"},
	'construction_cost_Metals', 15000,
	'construction_cost_MachineParts', 5000,
	'build_points', 2000,
	'is_tall', true,
	'dome_forbidden', true,
	'maintenance_resource_type', "Metals",
	'maintenance_resource_amount', 2000,
	'display_name', T{918395396463, --[[ModItemBuildingTemplate RSBSubsurfaceHeater display_name]] "Subsurface Heater"},
	'display_name_pl', T{614739169955, --[[ModItemBuildingTemplate RSBSubsurfaceHeater display_name_pl]] "Subsurface Heaters"},
	'description', T{962825857113, --[[ModItemBuildingTemplate RSBSubsurfaceHeater description]] "Increases the local temperature in cold areas and protects nearby buildings from Cold Waves."},
	'build_category', "Infrastructure",
	'display_icon', "UI/Icons/Buildings/subsurface_heater.tga",
	'build_pos', 9,
	'entity', "SubsurfaceHeater",
	'show_range_all', true,
	'encyclopedia_image', "UI/Encyclopedia/SubsurfaceHeater.tga",
	'label1', "OutsideBuildings",
	'palettes', "SubSurfaceHeater",
	'demolish_sinking', range(10, 15),
	'demolish_tilt_angle', range(300, 600),
	'electricity_consumption', 1600,
	'water_consumption', 1000,
	'air_consumption', 0,
}),
PlaceObj('ModItemBuildingTemplate', {
	'name', "RSBWindTurbine",
	'template_class', "RSBWindTurbine",
	'pin_rollover_context', "electricity",
	'pin_rollover_hint', T{807446466755, --[[ModItemBuildingTemplate RSBWindTurbine pin_rollover_hint]] "<image UI/Infopanel/left_click.tga 1400> Select"},
	'pin_rollover_hint_xbox', T{372121556605, --[[ModItemBuildingTemplate RSBWindTurbine pin_rollover_hint_xbox]] "<image UI/PS4/Cross.tga> View"},
	'construction_cost_Concrete', 4000,
	'construction_cost_MachineParts', 1000,
	'build_points', 1500,
	'is_tall', true,
	'dome_forbidden', true,
	'upgrade1_id', "WindTurbine_PolymerBlades",
	'upgrade1_display_name', T{382895791075, --[[ModItemBuildingTemplate RSBWindTurbine upgrade1_display_name]] "Polymer Blades"},
	'upgrade1_description', T{189983498734, --[[ModItemBuildingTemplate RSBWindTurbine upgrade1_description]] "+<upgrade1_mul_value_1>% Production."},
	'upgrade1_icon', "UI/Icons/Upgrades/polymer_blades_01.tga",
	'upgrade1_upgrade_cost_Polymers', 2000,
	'upgrade1_mod_label_1', "WindTurbine",
	'upgrade1_mod_prop_id_1', "electricity_production",
	'upgrade1_mul_value_1', 33,
	'maintenance_resource_type', "MachineParts",
	'maintenance_resource_amount', 500,
	'display_name', T{642376922230, --[[ModItemBuildingTemplate RSBWindTurbine display_name]] "Wind Turbine"},
	'display_name_pl', T{633700705268, --[[ModItemBuildingTemplate RSBWindTurbine display_name_pl]] "Wind Turbines"},
	'description', T{692362707627, --[[ModItemBuildingTemplate RSBWindTurbine description]] "Generates Power. Increased production during Dust Storms and at high elevations."},
	'build_category', "Power",
	'display_icon', "UI/Icons/Buildings/wind_turbine.tga",
	'build_pos', 3,
	'entity', "WindTurbine",
	'encyclopedia_text', T{259977522151, --[[ModItemBuildingTemplate RSBWindTurbine encyclopedia_text]] "Wind turbines generate electrical power from the Martian winds. The amount generated depends on how powerful the winds they are exposed to are, so proper positioning is essential as higher ground tends to be windier.\n\n<center><image UI/Common/rollover_line.tga 2000> <left>\n\nWhile wind speeds on Mars are generally mild, they can reach incredible speeds during dust storms. Still, the thin Martian atmosphere dictates that the average wind turbine would need winds around six times more powerful than those on Earth to create the same amount of thrust.\n \nThis technological challenge to take advantage of what little wind there is on Mars was solved by opting for vertical axis wind turbines, which are capable of catching the wind from all directions, instead of simply horizontal.  The materials used are light enough to self-start on much weaker forces than those most commonly used on Earth."},
	'encyclopedia_image', "UI/Encyclopedia/WindTurbine.tga",
	'entity2', "WindTurbineChrome",
	'entitydlc2', "dde",
	'label1', "OutsideBuildings",
	'label2', "OutsideBuildingsTargets",
	'palettes', "WindTurbine",
	'demolish_sinking', range(0, 0),
	'demolish_tilt_angle', range(300, 600),
	'demolish_debris', 85,
	'electricity_production', 5000,
	'bonus_per_kilometer_elevation', 300,
	'min_production_to_work', 0,
}),
PlaceObj('ModItemCode', {
	'name', "Breakthrough",
	'FileName', "Code/Breakthrough.lua",
}),
PlaceObj('ModItemCode', {
	'name', "Logging",
	'FileName', "Code/Logging.lua",
}),
PlaceObj('ModItemCode', {
	'name', "RSBDisasterControl",
	'FileName', "Code/RSBDisasterControl.lua",
}),
PlaceObj('ModItemCode', {
	'name', "TechMap",
	'FileName', "Code/TechMap.lua",
}),
PlaceObj('ModItemTech', {
	'name', "RSBBreakthroughBiotech",
	'id', "RSBBreakthroughBiotech",
	'display_name', T{361773802745, "Biotech deep research"},
	'icon', "UI/Icons/Research/biome_engineering.tga",
	'description', T{361773802799, "Advanced research in biotech. Tries to find a new breakthrough in biotech.<newline>Makes all colonists <param1comment> <param1>% less food when failed.<newline>After reaching minimal consumption rate grants <param2>% bonus to all funding gains."},
	'position', range(5, 5),
	'repeatable', true,
	'param1comment', "Consumption food decrease per fail <param1>%",
	'param1', 2,
	'param2comment', "Consumption minimum",
	'param2', 10,
	'param5comment', "Funding gain per fail",
	'param5', 2,
	'field', "Biotech",
}),
PlaceObj('ModItemTech', {
	'name', "RSBBreakthroughEngineering",
	'id', "RSBBreakthroughEngineering",
	'display_name', T{736758121526, "Engineering deep research"},
	'icon', "UI/Icons/Research/mars_nouveau.tga",
	'description', T{736758121599, "Advanced research in engineering. Tries to find a new breakthrough in enginnering.<newline>"},
	'position', range(5, 5),
	'repeatable', true,
	'param1', 500,
	'param2', 5000,
	'param5comment', "Funding gain per fail",
	'param5', 2,
	'field', "Engineering",
}),
PlaceObj('ModItemTech', {
	'name', "RSBBreakthroughPhysics",
	'id', "RSBBreakthroughPhysics",
	'display_name', T{908591358810, "Physics deep research"},
	'icon', "UI/Icons/Research/atomic_accumulator.tga",
	'description', T{908591358899, "Advanced research in engineering. Tries to find a new breakthrough in physics.<newline>Increases research output from electricity surplus when failed.<newline>After reaching minimal consumption rate grants bonus to all funding gains."},
	'position', range(5, 5),
	'repeatable', true,
	'param1comment', "Electricity units per research points (100 = 1EU)",
	'param1', 500,
	'param2comment', "Electricity minimum",
	'param2', 5000,
	'param5comment', "Funding gain per fail",
	'param5', 2,
	'field', "Physics",
}),
PlaceObj('ModItemTech', {
	'name', "RSBBreakthroughRobotics",
	'id', "RSBBreakthroughRobotics",
	'display_name', T{747721283307, "Robotics deep research"},
	'icon', "UI/Icons/Research/rover_command_ai.tga",
	'description', T{747721283399, "Advanced research in robotics: tries to find a new breakthrough in robotics.<newline>Increases all automated performance if failed by <param1>% up to <param2>% limit.<newline>After reaching maximum peformance grants <param5>% bonus to all funding gains."},
	'position', range(5, 5),
	'repeatable', true,
	'param1comment', "Automated robotics performance bonus, %",
	'param1', 5,
	'param2comment', "Automated robotics performance max, %",
	'param2', 100,
	'param5comment', "Funding gain per fail",
	'param5', 2,
	'field', "Robotics",
}),
PlaceObj('ModItemTech', {
	'name', "RSBBreakthroughSocial",
	'id', "RSBBreakthroughSocial",
	'display_name', T{930113112848, "Social deep research"},
	'icon', "UI/Icons/Research/general_training.tga",
	'description', T{930113112899, "Advanced research in social.<newline>Tries to find a new breakthrough in social.<newline>Gives <param5>% to all funding gains when failed."},
	'position', range(5, 5),
	'repeatable', true,
	'param5comment', "Funding gain per fail",
	'param5', 5,
	'field', "Social",
}),
}
